apiVersion: v1
kind: Template
labels:
  demo: mapit-template-ger
metadata:
  annotations:
    description: MapIt Ger
  name: mapit-ger
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
      application: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${APP_NAME}
parameters:
- displayName: Application name
  name: APP_NAME
  required: true
  value: ger

